# Site wide configuration

title:  Rosie's Blog
locale: en_UK
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Rosie Hamilton
  avatar: avatar.jpg
  bio: "Software Tester, Violinist, Gopher, Data Explorer, Yoga Addict, Honest Blogger, PC Gamer, Curious Learner, Creator of my own unique path through life."
  email:
  disqus-shortname:
  twitter: rosicadia
  facebook: rosie.hamilton.7982
  google:
    plus: RosieHamilton
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Rosalita
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: missrosalita
  lastfm: #username
  tumblr: #username
  pinterest: enchantrix
  foursquare: #username
  steam: MissRosalita
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
